# file: .travis.yml
branches:
 only:
 - master

xcode_project: Swifternalization.xcodeproj
xcode_scheme: SwifternalizationTests
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3

script:
- xcodebuild clean build test -travisSwift/travisSwift.xcodeproj -scheme travisSwift